### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by pati-ni** [califano-lab/ARACNe-AP#7]
Hi,

I find the instructions included in the page not sufficient for the installation. There are a lot of dependencies missing that I had to source from the apache commons and update my CLASSPATH. Dependencies needed to be manually loaded from source.

However jargs is not following the correct structure of the dependencies (See [https://github.com/purcell/jargs/tree/master/src/main/java/com/sanityinc/jargs]). jargs.gnu is not a thing:  `[javadoc] /mnt/c/Users/patou/data/git_repos/ARACNe-AP/aracne/Aracne.java:3: error: package jargs.gnu does not exist`

```
$ ant main
Buildfile: /mnt/c/Users/patou/data/git_repos/ARACNe-AP/build.xml

clean:
   [delete] Deleting directory /mnt/c/Users/patou/data/git_repos/ARACNe-AP/bin
   [delete] Deleting directory /mnt/c/Users/patou/data/git_repos/ARACNe-AP/docs
   [delete] Deleting directory /mnt/c/Users/patou/data/git_repos/ARACNe-AP/dist

makedir:
    [mkdir] Created dir: /mnt/c/Users/patou/data/git_repos/ARACNe-AP/bin
    [mkdir] Created dir: /mnt/c/Users/patou/data/git_repos/ARACNe-AP/docs
    [mkdir] Created dir: /mnt/c/Users/patou/data/git_repos/ARACNe-AP/dist

compile:
    [javac] /mnt/c/Users/patou/data/git_repos/ARACNe-AP/build.xml:28: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 8 source files to /mnt/c/Users/patou/data/git_repos/ARACNe-AP/bin
    [javac] /mnt/c/Users/patou/data/git_repos/ARACNe-AP/build.xml:35: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 4 source files to /mnt/c/Users/patou/data/git_repos/ARACNe-AP/bin
    [javac] Note: /mnt/c/Users/patou/data/git_repos/ARACNe-AP/aracne/Aracne.java uses or overrides a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: /mnt/c/Users/patou/data/git_repos/ARACNe-AP/aracne/MI.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.

jar:
      [jar] Building jar: /mnt/c/Users/patou/data/git_repos/ARACNe-AP/dist/aracne.jar

docs:
  [javadoc] Generating Javadoc
  [javadoc] Javadoc execution
  [javadoc] Loading source file /mnt/c/Users/patou/data/git_repos/ARACNe-AP/aracne/Aracne.java...
  [javadoc] Loading source file /mnt/c/Users/patou/data/git_repos/ARACNe-AP/aracne/BootstrapConsolidator.java...
  [javadoc] Loading source file /mnt/c/Users/patou/data/git_repos/ARACNe-AP/aracne/DPI.java...
  [javadoc] Loading source file /mnt/c/Users/patou/data/git_repos/ARACNe-AP/aracne/MI.java...
  [javadoc] Constructing Javadoc information...
  [javadoc] /mnt/c/Users/patou/data/git_repos/ARACNe-AP/aracne/Aracne.java:3: error: package jargs.gnu does not exist
  [javadoc] import jargs.gnu.CmdLineParser;
  [javadoc]                 ^
  [javadoc] Standard Doclet version 1.8.0_222
  [javadoc] Building tree for all the packages and classes...
  [javadoc] /mnt/c/Users/patou/data/git_repos/ARACNe-AP/aracne/MI.java:304: warning - @return tag has no arguments.
  [javadoc] Building index for all the packages and classes...
  [javadoc] Building index for all classes...
  [javadoc] Generating /mnt/c/Users/patou/data/git_repos/ARACNe-AP/docs/help-doc.html...
  [javadoc] 2 warnings

main:

BUILD SUCCESSFUL
Total time: 4 seconds
```

Any instructions on how to build the package?

**Comment by grosenberger** [comment]
Which version of Java are you using? Building ARACNe-AP with ``Java(TM) SE Runtime Environment (build 1.8.0_151-b12)`` worked without any external dependencies for me.

**Comment by pati-ni** [comment]
Hi @grosenberger 

thanks for your reply!

That's my version on linux debian environment:
```
$ java -version
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Debian-1bpo91)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Debian-1bpo91, mixed mode, sharing)
```


I will try to use the one you suggested and see if I manage to get it installed.

**Comment by mk1209567** [comment]
Hi @pati-ni 

I'm wondering did you solve the problem after using jdk1.8.0_151?

I encountered the same problem and installing jdk1.8.0_151 didn't solve my problem.
Thank you

**Comment by sudheshnabodapati** [comment]
Hi @pati-ni 

Wanted to know if you were able to install it, I'm seeing similar errors and would appreciate your help

**Comment by davidecarnevali** [comment]
Hi all,
same problem here.
I have these 2 modules loaded onto my HPC bash env:
Java/11.0.2 and  ant/1.10.8

when I run 'ant main' I get these errors:
Buildfile: /nfs/users/dcarnevali/Tools/ARACNe-AP-master/build.xml

clean:
   [delete] Deleting directory /nfs/users/dcarnevali/Tools/ARACNe-AP-master/bin
   [delete] Deleting directory /nfs/users/dcarnevali/Tools/ARACNe-AP-master/docs
   [delete] Deleting directory /nfs/users/dcarnevali/Tools/ARACNe-AP-master/dist

makedir:
    [mkdir] Created dir: /nfs/users/dcarnevali/Tools/ARACNe-AP-master/bin
    [mkdir] Created dir: /nfs/users/dcarnevali/Tools/ARACNe-AP-master/docs
    [mkdir] Created dir: /nfs/users/dcarnevali/Tools/ARACNe-AP-master/dist

compile:
    [javac] /nfs/users/dcarnevali/Tools/ARACNe-AP-master/build.xml:28: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 8 source files to /nfs/users/dcarnevali/Tools/ARACNe-AP-master/bin
    [javac] /nfs/users/dcarnevali/Tools/ARACNe-AP-master/build.xml:35: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 4 source files to /nfs/users/dcarnevali/Tools/ARACNe-AP-master/bin
    [javac] Note: /nfs/users/dcarnevali/Tools/ARACNe-AP-master/aracne/Aracne.java uses or overrides a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: /nfs/users/dcarnevali/Tools/ARACNe-AP-master/aracne/MI.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.

jar:
      [jar] Building jar: /nfs/users/dcarnevali/Tools/ARACNe-AP-master/dist/aracne.jar

docs:
  [javadoc] Generating Javadoc
  [javadoc] Javadoc execution
  [javadoc] Loading source file /nfs/users/dcarnevali/Tools/ARACNe-AP-master/aracne/Aracne.java...
  [javadoc] Loading source file /nfs/users/dcarnevali/Tools/ARACNe-AP-master/aracne/BootstrapConsolidator.java...
  [javadoc] Loading source file /nfs/users/dcarnevali/Tools/ARACNe-AP-master/aracne/DPI.java...
  [javadoc] Loading source file /nfs/users/dcarnevali/Tools/ARACNe-AP-master/aracne/MI.java...
  [javadoc] Constructing Javadoc information...
  [javadoc] /nfs/users/dcarnevali/Tools/ARACNe-AP-master/aracne/Aracne.java:3: error: package jargs.gnu does not exist
  [javadoc] import jargs.gnu.CmdLineParser;
  [javadoc]                 ^
  [javadoc] /nfs/users/dcarnevali/Tools/ARACNe-AP-master/aracne/Aracne.java:18: error: package common does not exist
  [javadoc] import common.DataParser;
  [javadoc]              ^
  [javadoc] /nfs/users/dcarnevali/Tools/ARACNe-AP-master/aracne/Aracne.java:19: error: package common does not exist
  [javadoc] import common.ExpressionMatrix;
  [javadoc]              ^
  [javadoc] 14 errors
  [javadoc] /nfs/users/dcarnevali/Tools/ARACNe-AP-master/aracne/BootstrapConsolidator.java:13: error: package org.apache.commons.math3.distribution does not exist
  [javadoc] import org.apache.commons.math3.distribution.PoissonDistribution;
  [javadoc]                                             ^
  [javadoc] /nfs/users/dcarnevali/Tools/ARACNe-AP-master/aracne/MI.java:17: error: package common does not exist
  [javadoc] import common.DataMatrix;
  [javadoc]              ^
  [javadoc] /nfs/users/dcarnevali/Tools/ARACNe-AP-master/aracne/MI.java:18: error: package common does not exist
  [javadoc] import common.DataVector;
  [javadoc]              ^
  [javadoc] /nfs/users/dcarnevali/Tools/ARACNe-AP-master/aracne/MI.java:19: error: package common does not exist
  [javadoc] import common.Methods;
  [javadoc]              ^
  [javadoc] /nfs/users/dcarnevali/Tools/ARACNe-AP-master/aracne/MI.java:207: error: cannot find symbol
  [javadoc] 			HashMap<String, DataVector> data,
  [javadoc] 			                ^
  [javadoc]   symbol:   class DataVector
  [javadoc]   location: class MI
  [javadoc] /nfs/users/dcarnevali/Tools/ARACNe-AP-master/aracne/MI.java:304: error: cannot find symbol
  [javadoc] 	public static double computeMI(DataVector vectorX, DataVector vectorY){
  [javadoc] 	                               ^
  [javadoc]   symbol:   class DataVector
  [javadoc]   location: class MI
  [javadoc] /nfs/users/dcarnevali/Tools/ARACNe-AP-master/aracne/MI.java:304: error: cannot find symbol
  [javadoc] 	public static double computeMI(DataVector vectorX, DataVector vectorY){
  [javadoc] 	                                                   ^
  [javadoc]   symbol:   class DataVector
  [javadoc]   location: class MI
  [javadoc] /nfs/users/dcarnevali/Tools/ARACNe-AP-master/aracne/MI.java:358: error: cannot find symbol
  [javadoc] 	public MI(DataMatrix data) {
  [javadoc] 	          ^
  [javadoc]   symbol:   class DataMatrix
  [javadoc]   location: class MI
  [javadoc] /nfs/users/dcarnevali/Tools/ARACNe-AP-master/aracne/MI.java:478: error: cannot find symbol
  [javadoc] 	public double calibrateMIThresholdNA(HashMap<String, DataVector> _data, int randomPaircount, double miPvalue, int _seed){
  [javadoc] 	                                                     ^
  [javadoc]   symbol:   class DataVector
  [javadoc]   location: class MI
  [javadoc] /nfs/users/dcarnevali/Tools/ARACNe-AP-master/aracne/MI.java:255: error: cannot find symbol
  [javadoc] 		private HashMap<String, DataVector> data;
  [javadoc] 		                        ^
  [javadoc]   symbol:   class DataVector
  [javadoc]   location: class MI.MIThreadNA
  [javadoc] /nfs/users/dcarnevali/Tools/ARACNe-AP-master/aracne/MI.java:268: error: cannot find symbol
  [javadoc] 		MIThreadNA(String[] _tfs, String[] _genes, HashMap<String, DataVector> _rd1, double _mi, int _tfNumber) {
  [javadoc] 		                                                           ^
  [javadoc]   symbol:   class DataVector
  [javadoc]   location: class MI.MIThreadNA

main:

BUILD SUCCESSFUL
Total time: 3 seconds



any hint?

**Comment by pati-ni** [comment]
Hi @mk1209567 @sudheshnabodapati .

That was ages ago but I vaguely remember that it I managed to install it using Oracle Java. I can not confirm at the moment

**Comment by grosenberger** [comment]
That seems to only affect the documentation, right? The jar in `/nfs/users/dcarnevali/Tools/ARACNe-AP-master/dist/aracne.jar`, was built, right?

**Comment by davidecarnevali** [comment]
Yes, the aracne.jar is built but when I run it I get this error
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index
249 out of bounds for length 249
at common.ExpressionMatrix.<init>(Unknown Source)
at aracne.Aracne.runThreshold(Unknown Source)
at aracne.Aracne.main(Unknown Source)

But now I understood why.... my matrix header lacked the first column name
after saving the table from the R matrix
Now it works

Sorry and thank you
